---
- name: Instalar o Nginx
  package: 
    name: nginx
    state: latest
  tags: configure_nginx

- name: Inicializar o Nginx
  service:
    name: nginx 
    state: started
    enabled: true
  tags: configure_nginx

- name: Cria arquivo vhost
  copy:
    src: templates/vhost.conf.j2
    dest: /etc/nginx/conf.d/
  notify: restart nginx
  tags: configure_nginx
