version: '3.3'

services:
  db:
    image: "mysql:5.7"
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "4linux-desafio-2021"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "4linux-desafio-2021"

  wordpress:
    depends_on:
    - db
    image: wordpress:latest
    ports:
    - "{{ wordpress_ports }}"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "4linux-desafio-2021"
volumes:
  db_data: 